server.port=${SERVER_PORT}
server.servlet.context-path=/${SERVICE_NAME}

spring.main.allow-bean-definition-overriding=true
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.rabbitmq.host=${RABBITMQ_HOST:localhost}
spring.rabbitmq.port=${RABBITMQ_PORT:5672}
spring.rabbitmq.password=${RABBITMQ_PASSWORD:admin}
spring.rabbitmq.username=${RABBITMQ_USERNAME:admin}

resend.api-key=${RESEND_API_KEY}
resend.from=${RESEND_FROM:SmartReport <no-reply@smartverse.com.br>}
app.frontend.base-url=${FRONTEND_BASE_URL:http://localhost:4200}
payment-service.base-url=${PAYMENT_SERVICE_BASE_URL:https://app.smartverse.com.br/api/payment-service}

app-config.secret.api-secret=YXV0aCBhcGkgc2VyY3JldCA1NTM2NA==

rabbit.exchange.name=router.api
rabbit.routingKey.name=router.product-inbox
rabbit.queue.name=product.queue
